apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-creative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-creative
  template:
    metadata:
      labels:
        app: mc-creative
    spec:
      nodeSelector:
        kubernetes.io/hostname: saba2
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java25
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: GAMEMODE
              value: "creative"
            - name: FORCE_GAMEMODE
              value: "TRUE"
            - name: DIFFICULTY
              value: "peaceful"
            - name: SPAWN_PROTECTION
              value: "0"
            - name: LEVEL_TYPE
              value: "flat"
            - name: GENERATE_STRUCTURES
              value: "FALSE"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-auth
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: creative
      volumes:
        - name: data
          hostPath:
            path: /srv/minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: creative
spec:
  type: NodePort
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
    - name: rcon
      port: 25575
      targetPort: 25575
  selector:
    app: mc-creative
