apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      nodeSelector:
        kubernetes.io/hostname: saba2
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: root-data
              mountPath: /srv
            - name: config-data
              mountPath: /database.db
              subPath: filebrowser.db
      volumes:
        - name: root-data
          hostPath:
            path: /srv/minecraft
            type: Directory
        - name: config-data
          hostPath:
            path: /srv/minecraft
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
