apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-survival
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-survival
  template:
    metadata:
      labels:
        app: mc-survival
    spec:
      nodeSelector:
        kubernetes.io/hostname: saba2
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java25
          resources:
            requests:
              memory: "12Gi"
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: 1.21.11
            - name: MEMORY
              value: "12G"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: RCON_PORT
              value: "25575"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-auth
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: survival
      volumes:
        - name: data
          hostPath:
            path: /srv/minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: survival
spec:
  type: NodePort
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: 25575
      nodePort: 30575
      protocol: TCP
  selector:
    app: mc-survival
