apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttyd
  template:
    metadata:
      labels:
        app: ttyd
    spec:
      containers:
        - name: ttyd
          image: itzg/minecraft-server:java25
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && apt-get install -y ttyd
              ttyd -p 7681 bash
          env:
            - name: RCON_HOST
              value: "survival"
            - name: RCON_PORT
              value: "25575"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-auth
                  key: password
          ports:
            - containerPort: 7681
