apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-proxy
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      nodeSelector:
        kubernetes.io/hostname: saba2
      containers:
        - name: velocity
          image: itzg/minecraft-server:latest
          env:
            - name: TYPE
              value: "VELOCITY"
            - name: VELOCITY_VERSION
              value: "LATEST"
            - name: MEMORY
              value: "1G"
          ports:
            - containerPort: 25577
              name: velocity
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-auth
                  key: key
